### ISSUE TITLE
Server disconnects after 20 seconds

### ISSUE THREAD

**Issue by brothercorvo** [Tapawingo/TAKlib#17]
<?xml version="1.0"?>\\n<event version="2.0" uid="ANDROID-XXXXXXXXXXXX-ping" type="t-x-c-t" time="2020-04-09T05:09:55.712Z" start="2020-04-09T05:09:55.712Z" stale="2020-04-09T05:10:05.712Z" how="m-g"><point lat="0.00000000" lon="0.00000000" hae="0.00000000" ce="9999999" le="9999999"/><detail/></event>'

<Element 'event' at 0x7f29ce4ded68>

uid is ANDROID-XXXXXXXXXXXX-ping

is ping

client disconnected now setting as disconnected

^CTraceback (most recent call last):

File "TAKFreeServer.py", line 199, in <module>

ThreadedServer('',port_num).listen()

File "TAKFreeServer.py", line 40, in listen

client, address = self.sock.accept()

File "/usr/lib64/python3.6/socket.py", line 205, in accept

fd, addr = self._accept()

KeyboardInterrupt

**Comment by brothercorvo** [comment]
Solved in c881750
